### ISSUE TITLE
Use Jankson instead of Gson to parse JSON5 configs

### ISSUE THREAD

**Issue by pkstDev** [KrLite/Plume-Config#1]
I just saw that you switched from `.properties` to `.json5` for configs, but weirdly you are still using `Gson`, which is for parsing original JSONs.

You can use `Jankson` for parsing JSON5 files. Its structure is fairly similar to `Gson`, but it comes with extra features like comments (JSON doesn't support comments and thus `Gson` doesn't contain anything for parsing comments while JSON5 do). You can have a look [here](https://github.com/falkreon/Jankson).

**Comment by pkstDev** [comment]
Also can you support multiple formats? I prefer to use TOML, but since this is meant to be lightweight, it'll be okay if you stick to JSON5 :)

**Comment by JieningYu** [comment]
> meant

你说的对，但本来是要用quilt json5的，后来发现导包没导成。

**Comment by KrLite** [comment]
It seems that using `Jackson` is undoubtedly a better way since I have been troubled by `GSON`'s shortcomings in `.json5` format for a period of time. Also, the proposal of supporting multiple formats which is certainly very constructive will be put on the agenda soon.

**Thanks again for those friendly suggestions!**

**Comment by KrLite** [comment]
Seems it's not quite easy to migrate to `Jankson` as it is using annotations and flexible instances.
I'm having no ideas now since `Jankson` is already a perfect tool which doesn't need no wrap. So this project may be stashed until someday I figure out something unique.

ps. This decision yet probably makes no impact to the community because no one uses my lib lol.

**Comment by KrLite** [comment]
Now it comes to be using [tomlj](https://github.com/tomlj/tomlj) to parse files, and I wrote a file structurer to write into the files. It works fine, but still not supporting all the toml features.

Toml is better than json5 for storing configs, I think. So json families are out of support now.
